### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buffer' of undefined

### ISSUE THREAD

**Issue by codeOfRobin** [shd101wyy/atom-markdown-katex#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.11
**Thrown From**: [atom-markdown-katex](https://github.com/shd101wyy/atom-markdown-katex) package, v0.3.2

### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of undefined

```
At /Users/robinmalhotra/.atom/packages/atom-markdown-katex/lib/atom-markdown-katex.js:117

TypeError: Cannot read property 'buffer' of undefined
  at atom-workspace.beginMarkdownKatexPreview (/Users/robinmalhotra/.atom/packages/atom-markdown-katex/lib/atom-markdown-katex.js:117:31)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -9:08.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -9:07.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:03.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -9:03.0 core:move-up (atom-text-editor.editor.is-focused)
     -9:02.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -9:02.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -8:57.4.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -8:55.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:48.5.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -7:19 core:backspace (atom-text-editor.editor.mini.is-focused)
     -7:06.0 markdown-preview-plus:toggle (atom-text-editor.editor.mini.is-focused)
     -4:16.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -3:51.5.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  3x -0:03.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 markdown-katex-preview:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.11
atom-markdown-katex, v0.3.2
autoclose-html, v0.18.0
color-picker, v2.0.11
minimap, v4.12.3

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
I just met the same problem, and I solved it by restarting the atom.

**Comment by B1T0** [comment]
Yeah, restarting also worked for me :+1:
