### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Element': '#1' is not a valid selector.

### ISSUE THREAD

**Issue by mistguy** [shd101wyy/atom-markdown-katex#11]
(1) enter some simple markdown contents:
```markdown
# test

# 1

This is a test

# 2

This is a test

# 3

This is a test
```
(2) generate toc

**Atom Version**: 1.6.2
**System**: linux 4.4.5-1-ARCH
**Thrown From**: [atom-markdown-katex](https://github.com/shd101wyy/atom-markdown-katex) package, v0.5.0

### Stack Trace

Uncaught SyntaxError: Failed to execute 'querySelector' on 'Element': '#1' is not a valid selector.

```
At /home/wangc/.atom/packages/atom-markdown-katex/lib/md-preview.js:39

Error: Failed to execute 'querySelector' on 'Element': '#1' is not a valid selector.
    at Error (native)
    at bindTagAClickEvent (/home/wangc/.atom/packages/atom-markdown-katex/lib/md-preview.js:39:46)
    at renderMarkdown (/home/wangc/.atom/packages/atom-markdown-katex/lib/md-preview.js:69:5)
    at updateMarkdown (/home/wangc/.atom/packages/atom-markdown-katex/lib/md-preview.js:180:11)
    at /home/wangc/.atom/packages/atom-markdown-katex/lib/md-preview.js:206:13
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1327:25
```

### Commands

```
     -1:13 command-palette:toggle (atom-pane.pane.active)
  3x -1:10.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:10.2.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -1:10 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:10 application:add-project-folder (atom-pane.pane.active)
     -0:18.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:17.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:14.2.0 markdown-katex-preview:toggle (atom-text-editor.editor.mini.is-focused)
     -0:11.9.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:09.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:08.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.2.0 markdown-katex-preview:toc-create (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -0:02.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.0 markdown-katex-preview:toc-create (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "welcome",
      "markdown-preview"
    ]
  },
  "atom-markdown-katex": {
    "useGitHubStyle": true,
    "useGitHubSyntaxTheme": true
  }
}
```

### Installed Packages

```coffee
# User
atom-markdown-katex, v0.5.0
autocomplete-python, v1.7.2
file-icons, v1.7.1
language-haskell, v1.7.10
language-latex, v0.6.1
language-pfm, v0.82.0
minimap, v4.21.0
minimap-bookmarks, v0.3.0

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
@mistguy Fixed.

Cheers

**Comment by mistguy** [comment]
confirm fixed
