### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of null

### ISSUE THREAD

**Issue by mistguy** [shd101wyy/atom-markdown-katex#14]
1. open a markdown file(preview automatically opens)
2. close preview
3. use ctrl+alt+O to open preview again
4. close markdown editor pane

**Atom Version**: 1.7.1
**System**: linux 4.5.0-1-ARCH
**Thrown From**: [atom-markdown-katex](https://github.com/shd101wyy/atom-markdown-katex) package, v0.5.3

### Stack Trace

Uncaught TypeError: Cannot read property 'destroy' of null

```
At /home/wangc/.atom/packages/atom-markdown-katex/lib/md-preview.js:144

TypeError: Cannot read property 'destroy' of null
    at disposables.add.editor.onDidDestroy (/home/wangc/.atom/packages/atom-markdown-katex/lib/md-preview.js:144:29)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.destroyed (/usr/share/atom/resources/app.asar/src/text-editor.js:295:27)
    at TextEditor.module.exports.Model.destroy (/usr/share/atom/resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:639:18)
    at atom-tabs.TabBarView.onClick (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:658:17)
```

### Commands

```
     -1:11.8.0 markdown-katex-preview:toggle (atom-text-editor.editor.is-focused)
     -1:08.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:03.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:03.8.0 markdown-katex-preview:toc-create (atom-text-editor.editor)
     -0:41.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:38 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:25.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:18.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:04.1.0 markdown-katex-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "welcome",
      "markdown-preview"
    ]
  },
  "atom-markdown-katex": {
    "pdfUseGithub": false
  }
}
```

### Installed Packages

```coffee
# User
atom-markdown-katex, v0.5.3
autocomplete-python, v1.7.2
file-icons, v1.7.3
language-haskell, v1.7.10
language-latex, v0.6.1
language-pfm, v0.82.0
minimap, v4.22.1
minimap-bookmarks, v0.3.0

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
thx, should be fixed

**Comment by mistguy** [comment]
confirm fixed
